# Generated by Django 5.1.5 on 2025-02-06 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "respondent_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Student", "Student"),
                            ("Colleague", "Colleague"),
                            ("Administrative Staff", "Administrative Staff"),
                            ("Parent", "Parent"),
                            ("Self", "Self (for self-assessment)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                ("feedback_date", models.DateField()),
                ("strengths", models.TextField(blank=True, null=True)),
                ("improvement", models.TextField(blank=True, null=True)),
                ("impact_instance", models.TextField(blank=True, null=True)),
                ("additional_comments", models.TextField(blank=True, null=True)),
                (
                    "overall_rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No"), ("Maybe", "Maybe")],
                        max_length=10,
                    ),
                ),
                ("development_suggestions", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
